### ISSUE TITLE
Use mm class where applicable.

### ISSUE THREAD

**Issue by mhulse** [mhulse/html-starter-kit#6]

**Comment by mhulse** [comment]
Nope. Going to stick to ONLY html examples. Save my best CSS snippets for another repo or something.

Here's what I removed:

``` css
// Responsive helpers:
embed,
iframe,
img,
object,
video { max-width: 100%; }
img { height: auto; }
audio,
video {
    vertical-align: middle;
    display: block;
}
audio { width: 100%; }
.mm {

    height: 0;
    padding-bottom: 56.25%; // 16:9 = (9 / 16 = .5625) x 100
    position: relative;
    overflow: hidden;

    iframe,
    object,
    embed,
    video {
        border: 0;
        width: 100% !important;
        height: 100% !important;
        max-width: none;
        position: absolute;
        top: 0;
        left: 0;
    }

    &.theatre { padding-bottom: 59.171597633136%; } // 1.69:1 = (1 / 1.69 = .59171597633136) x 100

    &.slide { padding-bottom: 66.666666666667%; } // 3:2 = (2 / 3 = .66666666666667) x 100

    &.tv { padding-bottom: 75%; } // 4:3 = (3 / 4 = .75) x 100

}
pre {
    font-family: monospace, serif;
    word-wrap: normal;
    overflow: auto;
    white-space: pre;
}
```
